### ISSUE TITLE
Let's make error readable.

### ISSUE THREAD

**Issue by nandgator** [athul/jiofi-cli#2]
**Scenario**: I'm not connected to JioFi. Running the program generates:

```python
joe733 in jiofi-cli at xpsl502x on ⎇ master via 🅒 jiofi
➜ python main.py basic
Traceback (most recent call last):
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd71d8fa5e0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='jiofi.local.html', port=80): Max retries exceeded with url: /cgi-bin/qcmap_web_cgi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd71d8fa5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 107, in <module>
    fire.Fire({
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "main.py", line 99, in getBasicDetails
    bats = deviceDetails(False)
  File "main.py", line 59, in deviceDetails
    res = requests.post(URL,form)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='jiofi.local.html', port=80): Max retries exceeded with url: /cgi-bin/qcmap_web_cgi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd71d8fa5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
Catch the exeption and print out: `Please double check if you are connected to JioFi hotspot`

**Comment by nandgator** [comment]
Oops! little late :wink:. I think #1 resolves it.

**Comment by athul** [comment]
Could you try upgrading the package and run again?

Don't close it yet

**Comment by nandgator** [comment]
Hey, @athul  I've a doubt. I forked your repo and I try to sync it with [pull-bot](https://wei.github.io/pull/). But I've to wait for it to sync the repo. Now my fork is 3 commits behind yours so how can I manually sync it without adding additional commits. This `https://pull.git.ci/process/${athul}/${jiofi-cli}` method (as mentioned in the website) does not work.

**Comment by athul** [comment]
@joe733 I haven't used that yet and haven't got any idea on how to resolve that issue. I'm really sorry. 

I looked into that traceback and there seems to be a lot of them and the solution I could bring up was

```py
import requests
import socket
from urllib3.exceptions import NewConnectionError,MaxRetryError
try:
        res = requests.post(URL,form)
except requests.ConnectionError or NewConnectionError or MaxRetryError or socket.gaierror:
        print("Connect to a Jiofi Network to get the details")
        sys.exit(1)
```

When using the script, it tends to work when I simple add the `requests.ConnectionError` in the except statement

**Comment by nandgator** [comment]
Yes #1 works when not connected to JioFi

![Screenshot from 2020-07-28 09-30-02](https://user-images.githubusercontent.com/38415384/88617765-1351b000-d0b5-11ea-8818-b8d4ced69c19.png)

**Comment by athul** [comment]
Nope, not like this. Could you try
```shell
pip install jiofi
```
And run the commands of jiofi

**Comment by nandgator** [comment]
Oh okay `jiofi basic` does produce these errors when not connected to a JioFi network.

```python
joe733 in jiofi-cli at xpsl502x on  master via 🅒 jiofi 
➜ jiofi basic
Traceback (most recent call last):
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f86c7ebb8b0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='jiofi.local.html', port=80): Max retries exceeded with url: /cgi-bin/qcmap_web_cgi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86c7ebb8b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joe733/anaconda3/envs/jiofi/bin/jiofi", line 8, in <module>
    sys.exit(main())
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/jiofi/jiofi.py", line 106, in main
    fire.Fire({
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/jiofi/jiofi.py", line 99, in getBasicDetails
    bats = deviceDetails(False)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/jiofi/jiofi.py", line 59, in deviceDetails
    res = requests.post(URL,form)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/joe733/anaconda3/envs/jiofi/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='jiofi.local.html', port=80): Max retries exceeded with url: /cgi-bin/qcmap_web_cgi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86c7ebb8b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by athul** [comment]
Check the NewRelease. It will Work I guess.

`pip install --upgrade jiofi --user`

**Comment by athul** [comment]
Guess #4 closes this

**Comment by nandgator** [comment]
Yea it does. Closing the issue.

![Screenshot from 2020-08-04 20-30-11](https://user-images.githubusercontent.com/38415384/89309707-63baa600-d691-11ea-8a2d-dc5807261de0.png)
